### ISSUE TITLE
SysWhispers2

### ISSUE THREAD

**Issue by evandrix** [ajpc500/NimlineWhispers#3]
https://github.com/jthuraisamy/SysWhispers2

**Comment by chvancooten** [comment]
I just verified that you can use SysWhispers 2 just fine! Grab the output `.asm` and `.h` files from SysWhispers 2 and put those in your Nimline Whispers directory before generating :)

**Comment by chvancooten** [comment]
I agree that porting to this will be useful, since Syswhispers2 is capable of resolving syscall addresses dynamically and it avoids the situation where syscalls cannot be resolved after newer builds (such as now, with Windows 21H1 / Build 19043, refer to issue here: https://github.com/jthuraisamy/SysWhispers/issues/12).

However, implementing this would be non-trivial since the included C functions for dynamic resolving of the syscall indexes also need to be ported to Nim.

**Comment by chvancooten** [comment]
@evandrix @ajpc500 

I've spent a couple of hours trying to get Syswhispers2 to work in Nim but unfortunately seem to have hit a wall. After some effort (see steps below) I got it to compile, but actually calling the functions in Nim seems to result in a fatal error. As I'm not too skilled with debuggers or otherwise low-level troubleshooting I'm not sure if I can pick this up further :/

Gist here: https://gist.github.com/chvancooten/083dbdfd4a10261ee8dfecb4caf07e6c

Rough steps to get Nim to compile:
1. Generate Syswhispers2 files for the right functions with `python .\syswhispers.py --functions NtAllocateVirtualMemory,NtWriteVirtualMemory,NtOpenProcess,NtCreateThreadEx,NtClose,NtProtectVirtualMemory -o C:\Users\Username\Downloads\syscalls`.
2. Add output file `syscalls.c` to `syscalls.nim` via `.emit`.
3. Ensure the `include` statement in the C source can find your `syscalls.h` file.
4. Comment out duplicate struct definitions in `syscalls.h` (see Gist, or just follow the compiler errors lol).
5. Update Nim function definitions with inline assembly from the `syscallsstubs.asm` file.
6. Update hexadecimal values in inline assembly (end with `h`) to decimal.
7. Compile!
8. Do not profit :(

My suspicion is that the inline assembly for the `call SW2_GetSyscallNumber` instruction cannot find the appropriate function, even though it is defined in the C code and Nim code as well...

If you have some spare time - I think this would be a valuable update to Nimline whispers, rather than just being at the mercy of SysWhispers1 being updated :)

**Comment by NotoriousRebel** [comment]
@chvancooten Any updates to this?

**Comment by chvancooten** [comment]
@NotoriousRebel Unfortunately I haven't looked into the issue any further. It should be possible though, so feel free ;)

**Comment by zhangding222** [comment]
21H1(19043.1320) not support

**Comment by ajpc500** [comment]
@zhangding222 is this still a problem having pulled with this PR merged? https://github.com/ajpc500/NimlineWhispers/pull/5

**Comment by zhangding222** [comment]
I've tried the solution, but it seem still not work
![image](https://user-images.githubusercontent.com/42668898/140374974-d265c6ce-0ae0-476a-a07e-d99490299d36.png)

**Comment by chvancooten** [comment]
Update to this: @yamakadi figured out how to get SysWhispers2 to work with Nim! Find his solution here: https://gist.github.com/chvancooten/083dbdfd4a10261ee8dfecb4caf07e6c#gistcomment-3989360

**Comment by yamakadi** [comment]
I am not sure how easy it would be to make it work the way NimlineWhispers works right now, but these are the steps I followed:

- Use [SysWhispers2BOF](https://github.com/FalconForceTeam/SysWhispers2BOF) to generate `syscalls.h`
- Use NimlineWhispers to generate `syscalls.nim` for the same functions
- Replace the asm blocks from `syscalls.nim` with the ones from `syscalls.h`
- Copy the SW2_ related definitions and functions from `syscalls.h` to an emit block in `syscalls.nim`.

As long as the SW2_* stuff remains in an emit block, things seem to work fine.

**Comment by ajpc500** [comment]
This is great @yamakadi @chvancooten, thank you. Got some tidying up before I put the code up but... 👀

![image](https://user-images.githubusercontent.com/62765165/146991028-7844f255-e6d4-4293-892d-42ac18a45ab3.png)
